plugins {
    id("java-test-fixtures")
}
apply from: "${project.rootDir}/gradle/kotlin-plugin.gradle"
apply from: "${project.rootDir}/gradle/in-test-generated.gradle"

dependencies {
    implementation(projects.core.symbolProcessorCommon)
    implementation(projects.core.koraAppSymbolProcessor)
    implementation(projects.aop.aopSymbolProcessor)

    testImplementation(testFixtures(projects.core.annotationProcessorCommon))
    testImplementation(testFixtures(projects.core.symbolProcessorCommon))
    testImplementation(projects.validation.validationCommon)
    testImplementation(projects.internal.testLogging)
    testImplementation(projects.core.symbolProcessorCommon)
    testImplementation(projects.config.configSymbolProcessor)
    testImplementation(projects.core.koraAppSymbolProcessor)
    testImplementation(projects.json.jsonCommon)
    testImplementation(libs.kotlin.stdlib.lib)
}
