package io.koraframework.resilient.distributed.ratelimiter;

import io.koraframework.resilient.ratelimiter.RateLimiter;
import io.koraframework.resilient.ratelimiter.exception.RateLimitExceededException;
import io.koraframework.resilient.ratelimiter.telemetry.RateLimiterTelemetry;

/**
 * Single-key distributed {@link RateLimiter} that selects a concrete algorithm from
 * {@link DistributedRateLimiterConfig#algorithm()} and delegates to it — the distributed counterpart of
 * {@link io.koraframework.resilient.ratelimiter.KoraRateLimiter}.
 *
 * <p>This is the base for the impl generated by {@code @RateLimiterDistributedSpec}, so a distributed limiter is a drop-in
 * {@code RateLimiter} usable by {@code @RateLimited}. Its Redis key is {@code keyPrefix:name} (fixed, one per spec);
 *
 * @see FixedWindowRateLimiter
 * @see TokenBucketRateLimiter
 */
public class KoraDistributedRateLimiter implements RateLimiter {

    private final RateLimiter delegate;

    public KoraDistributedRateLimiter(String name,
                                      DistributedRateLimiterConfig config,
                                      DistributedRateLimiterClient client,
                                      RateLimiterTelemetry telemetry) {
        final String keyBase = config.keyPrefix() + ':' + name;
        this.delegate = switch (config.algorithm()) {
            case FIXED_WINDOW -> new FixedWindowRateLimiter(name, keyBase, config, client, telemetry);
            case TOKEN_BUCKET -> new TokenBucketRateLimiter(name, keyBase, config, client, telemetry);
        };
    }

    @Override
    public boolean tryAcquire() {
        return delegate.tryAcquire();
    }

    @Override
    public void acquire() throws RateLimitExceededException {
        delegate.acquire();
    }

    RateLimiter delegate() {
        return this.delegate;
    }

    @Override
    public String toString() {
        return delegate.toString();
    }
}
