apply from: "${project.rootDir}/gradle/kotlin-plugin.gradle"
apply from: "${project.rootDir}/gradle/in-test-generated.gradle"

dependencies {
    implementation(projects.core.symbolProcessorCommon)
    implementation(projects.core.koraAppSymbolProcessor)
    implementation(libs.ksp.api)
    implementation(libs.kotlin.reflect)
    implementation(libs.kotlinpoet.ksp)

    testImplementation(testFixtures(projects.core.symbolProcessorCommon))
    testImplementation(projects.http.httpClientCommon)
    testImplementation(projects.config.configSymbolProcessor)
    testImplementation(projects.logging.loggingCommon)
    testImplementation(libs.mockito.kotlin)
    testImplementation(libs.kotlin.stdlib.lib)
}
