package io.koraframework.kora.app.annotation.processor.extension;

import com.palantir.javapoet.ClassName;
import org.jspecify.annotations.Nullable;
import io.koraframework.annotation.processor.common.CommonUtils;
import io.koraframework.annotation.processor.common.NameUtils;
import io.koraframework.annotation.processor.common.ProcessingErrorException;
import io.koraframework.kora.app.annotation.processor.exception.DependencySourceFormatter;

import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.element.Element;
import javax.lang.model.element.Modifier;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import java.io.IOException;

public interface KoraExtension {
    @Nullable
    KoraExtensionDependencyGenerator getDependencyGenerator(RoundEnvironment roundEnvironment, TypeMirror typeMirror, @Nullable String tag);

    interface KoraExtensionDependencyGenerator {
        ExtensionResult generateDependency() throws IOException;

        static KoraExtensionDependencyGenerator generatedFrom(Elements elements, Element element, ClassName postfix) {
            return generatedFrom(elements, element, postfix.simpleName());
        }

        static KoraExtensionDependencyGenerator generatedFrom(Elements elements, Element element, String postfix) {
            var generatedName = NameUtils.generatedType(element, postfix);
            return generatedFromWithName(elements, element, generatedName);
        }

        /**
         * Looks for the type nested into the holder generated for the element, e.g. <code>$Element_Holder.Nested</code>,
         * and if there is no such type for the top level type with the legacy name, e.g. <code>$Element_Legacy</code>,
         * that is generated by older processor versions and symbol processors.
         */
        static KoraExtensionDependencyGenerator generatedFromHolder(Elements elements, Element element, String holderPostfix, String nestedName, String legacyPostfix) {
            var holderName = NameUtils.generatedType(element, holderPostfix) + "." + nestedName;
            var legacyName = NameUtils.generatedType(element, legacyPostfix);
            return generatedFromWithName(elements, element, holderName, legacyName);
        }

        static KoraExtensionDependencyGenerator generatedFromWithName(Elements elements, Element element, String name) {
            return generatedFromWithName(elements, element, name, null);
        }

        private static KoraExtensionDependencyGenerator generatedFromWithName(Elements elements, Element element, String name, @Nullable String fallbackName) {
            var packageElement = elements.getPackageOf(element);

            return () -> {
                var maybeGenerated = elements.getTypeElement(packageElement.getQualifiedName() + "." + name);
                if (maybeGenerated == null && fallbackName != null) {
                    maybeGenerated = elements.getTypeElement(packageElement.getQualifiedName() + "." + fallbackName);
                }
                if (maybeGenerated == null) {
                    throw new ProcessingErrorException("""
                        Generated dependency class was not found:
                          expected type: %s

                        Fix:
                          - Ensure the annotation processor that generates this type is enabled.
                          - Compile again after fixing earlier annotation processing errors.
                        """.formatted(packageElement.getQualifiedName() + "." + name).stripTrailing(), element);
                }
                if (!CommonUtils.hasAopAnnotations(maybeGenerated)) {
                    var constructors = CommonUtils.findConstructors(maybeGenerated, m -> m.contains(Modifier.PUBLIC));
                    if (constructors.size() != 1) {
                        throw new ProcessingErrorException("""
                            Generated dependency class must have exactly one public constructor:
                              generated type: %s
                              found: %s

                            Fix:
                              - Check the processor that generated this class.
                              - If this type is generated by Kora, report this as a Kora bug.
                            """.formatted(maybeGenerated.getQualifiedName(), DependencySourceFormatter.constructors(constructors)).stripTrailing(), maybeGenerated);
                    }
                    return ExtensionResult.fromExecutable(constructors.get(0));
                }
                var aopProxy = NameUtils.generatedType(maybeGenerated, "_AopProxy");
                var aopProxyElement = elements.getTypeElement(packageElement.getQualifiedName() + "." + aopProxy);
                if (aopProxyElement == null) {
                    // aop annotation processor will handle it
                    throw new ProcessingErrorException("""
                        Generated AOP proxy class was not found:
                          expected type: %s

                        Fix:
                          - Ensure the AOP annotation processor is enabled.
                          - Compile again after fixing earlier AOP processing errors.
                        """.formatted(packageElement.getQualifiedName() + "." + aopProxy).stripTrailing(), maybeGenerated);
                }
                var constructors = CommonUtils.findConstructors(aopProxyElement, m -> m.contains(Modifier.PUBLIC));
                if (constructors.size() != 1) {
                    throw new ProcessingErrorException("""
                        Generated AOP proxy class must have exactly one public constructor:
                          generated type: %s
                          found: %s

                        Fix:
                          - Check the AOP processor that generated this class.
                          - If this type is generated by Kora, report this as a Kora bug.
                        """.formatted(aopProxyElement.getQualifiedName(), DependencySourceFormatter.constructors(constructors)).stripTrailing(), aopProxyElement);
                }
                return ExtensionResult.fromExecutable(constructors.get(0));
            };
        }
    }
}
