# we don't need it in our libraries
kotlin.stdlib.default.dependency=false
kotlin.incremental=true
kotlin.compiler.execution.strategy=daemon

##### GRADLE #####
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.tooling.models.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configureondemand=true
org.gradle.isolated-projects=true

org.gradle.jvmargs=-Xmx6g -Xms2g \
  -XX:+UseParallelGC \
  -Dfile.encoding=UTF-8 \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED

group=io.koraframework
version=2.0.0-SNAPSHOT

systemProp.gradle.internal.http.connectionTimeout=120000
systemProp.gradle.internal.http.socketTimeout=120000
systemProp.gradle.internal.network.retry.max.attempts=15
systemProp.gradle.internal.network.retry.initial.backoff=2000
