apply from: "${project.rootDir}/gradle/in-test-generated.gradle"

dependencies {
    implementation(projects.aop.aopAnnotationProcessor)

    testImplementation(projects.logging.loggingCommon)
    testImplementation(projects.json.jsonAnnotationProcessor)
    testImplementation(projects.core.koraAppAnnotationProcessor)
    testImplementation(projects.logging.loggingLogback)
    testImplementation(testFixtures(projects.core.annotationProcessorCommon))
}
