dependencies {
    api(projects.core.applicationGraph)
    api(projects.telemetry.micrometerCommon)
    api(libs.slf4j.api)
    api(libs.opentelemetry.api)
}

def generateKoraVersion = project.tasks.register("generateKoraVersion") { task ->
    def dirPath = "build/kora-version"
    def filePath = "${dirPath}/META-INF/kora/version/${project.name}"

    task.outputs.file(filePath)

    task.doLast {
        def output = file(filePath)
        output.parentFile.mkdirs()
        if (output.exists()) {
            output.delete()
        }
        output.createNewFile()
        output.write(version.toString())
    }
}

sourceSets {
    main {
        resources {
            srcDir(generateKoraVersion.map { "build/kora-version" })
        }
    }
}

sourcesJar.dependsOn(generateKoraVersion)
