<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="NPService" targetNamespace="Numlex" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="Numlex" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">

<wsdl:types>
	<xsd:schema elementFormDefault="qualified" targetNamespace="Numlex">
		<xsd:element name="ProcessMessage">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element minOccurs="0" name="xmlMessage" nillable="true" type="xsd:string"/>
				</xsd:sequence>
			</xsd:complexType>
		</xsd:element>
		
		<xsd:element name="ProcessMessageResponse">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element minOccurs="0" name="ProcessMessageResult" nillable="true" type="tns:NPResponse"/>
				</xsd:sequence>
			</xsd:complexType>
		</xsd:element>
		
		<xsd:complexType name="NPResponse">
			<xsd:sequence>
				<xsd:element minOccurs="0" name="StatusCode" type="xsd:int"/>
				<xsd:element minOccurs="0" name="StatusMessage" nillable="true" type="xsd:string"/>
			</xsd:sequence>
		</xsd:complexType>
		
		<xsd:element name="NPResponse" nillable="true" type="tns:NPResponse"/>
	</xsd:schema>
	
	<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/">
		<xs:element name="anyType" nillable="true" type="xs:anyType"/>
		<xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
		<xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
		<xs:element name="boolean" nillable="true" type="xs:boolean"/>
		<xs:element name="byte" nillable="true" type="xs:byte"/>
		<xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
		<xs:element name="decimal" nillable="true" type="xs:decimal"/>
		<xs:element name="double" nillable="true" type="xs:double"/>
		<xs:element name="float" nillable="true" type="xs:float"/>
		<xs:element name="int" nillable="true" type="xs:int"/>
		<xs:element name="long" nillable="true" type="xs:long"/>
		<xs:element name="QName" nillable="true" type="xs:QName"/>
		<xs:element name="short" nillable="true" type="xs:short"/>
		<xs:element name="string" nillable="true" type="xs:string"/>
		<xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
		<xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
		<xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
		<xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
		<xs:element name="char" nillable="true" type="tns:char"/>
		<xs:simpleType name="char">
			<xs:restriction base="xs:int"/>
		</xs:simpleType>
		<xs:element name="duration" nillable="true" type="tns:duration"/>
		<xs:simpleType name="duration">
			<xs:restriction base="xs:duration">
				<xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
				<xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
				<xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
			</xs:restriction>
		</xs:simpleType>
		<xs:element name="guid" nillable="true" type="tns:guid"/>
		<xs:simpleType name="guid">
			<xs:restriction base="xs:string">
				<xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
			</xs:restriction>
		</xs:simpleType>
		<xs:attribute name="FactoryType" type="xs:QName"/>
		<xs:attribute name="Id" type="xs:ID"/>
		<xs:attribute name="Ref" type="xs:IDREF"/>
	</xs:schema>
</wsdl:types>

<wsdl:message name="NPService_ProcessMessage_InputMessage">
	<wsdl:part name="parameters" element="tns:ProcessMessage"/>
</wsdl:message>
<wsdl:message name="NPService_ProcessMessage_OutputMessage">
	<wsdl:part name="parameters" element="tns:ProcessMessageResponse"/>
</wsdl:message>

<wsdl:portType name="NPService">
	<wsdl:operation name="ProcessMessage">
		<wsdl:input wsaw:Action="Numlex/NPService/ProcessMessage" message="tns:NPService_ProcessMessage_InputMessage"/>
		<wsdl:output wsaw:Action="Numlex/NPService/ProcessMessageResponse" message="tns:NPService_ProcessMessage_OutputMessage"/>
	</wsdl:operation>
</wsdl:portType>

<wsdl:binding name="BasicHttpBinding_NPService" type="tns:NPService">
	<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
	<wsdl:operation name="ProcessMessage">
		<soap:operation soapAction="Numlex/NPService/ProcessMessage" style="document"/>
		<wsdl:input><soap:body use="literal"/></wsdl:input>
		<wsdl:output><soap:body use="literal"/></wsdl:output>
	</wsdl:operation>
</wsdl:binding>

<wsdl:service name="NPService">
	<wsdl:port name="BasicHttpBinding_NPService" binding="tns:BasicHttpBinding_NPService">
		<soap:address location="http://pilot.bdpn.ru/NPWS/NPservice.svc"/>
	</wsdl:port>
</wsdl:service>

</wsdl:definitions>