package io.koraframework.database.jdbc;

import io.koraframework.database.jdbc.exception.UncheckedSqlException;
import io.koraframework.database.jdbc.mapper.parameter.JdbcParameterColumnMapper;
import org.jspecify.annotations.Nullable;

import java.lang.reflect.Array;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLType;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import java.util.stream.Collectors;

final class JdbcQueryImpl implements JdbcQuery {

    private final String sourceSql;
    private final String sql;
    private final List<Parameter> parameters;
    private final JdbcQueryOptions options;

    private JdbcQueryImpl(String sourceSql, String sql, List<Parameter> parameters, JdbcQueryOptions options) {
        this.sourceSql = sourceSql;
        this.sql = sql;
        this.parameters = List.copyOf(parameters);
        this.options = Objects.requireNonNull(options);
    }

    static NamedQueryBuilder named() {
        return new NamedQueryBuilderImpl();
    }

    static TemplateBuilder template() {
        return new TemplateQueryBuilderImpl();
    }

    static OptsBuilder opts() {
        return new OptsBuilderImpl();
    }

    @Override
    public String sourceSql() {
        return this.sourceSql;
    }

    @Override
    public String sql() {
        return this.sql;
    }

    @Override
    public JdbcQueryOptions options() {
        return this.options;
    }

    @Override
    public List<Object> parameterValues() {
        return this.parameters.stream()
            .map(Parameter::value)
            .collect(Collectors.toUnmodifiableList());
    }

    @Override
    public List<Parameter> parameters() {
        return this.parameters;
    }

    @Override
    public PreparedStatement prepare(Connection connection) throws UncheckedSqlException {
        PreparedStatement statement = null;
        try {
            statement = prepareStatement(connection, this.sql, this.options);
            bindParameters(statement, this.parameters);
            return statement;
        } catch (SQLException e) {
            closeOnError(statement, e);
            throw new UncheckedSqlException(e);
        }
    }

    private static PreparedStatement prepareStatement(Connection connection, String sql, JdbcQueryOptions options) throws SQLException {
        PreparedStatement statement;
        if (!options.generatedKeyColumns().isEmpty()) {
            statement = connection.prepareStatement(sql, options.generatedKeyColumns().toArray(String[]::new));
        } else if (options.autoGeneratedKeys() != null) {
            statement = connection.prepareStatement(sql, options.autoGeneratedKeys());
        } else if (options.resultSetHoldability() != null) {
            statement = connection.prepareStatement(
                sql,
                options.resultSetType() == null ? ResultSet.TYPE_FORWARD_ONLY : options.resultSetType(),
                options.resultSetConcurrency() == null ? ResultSet.CONCUR_READ_ONLY : options.resultSetConcurrency(),
                options.resultSetHoldability()
            );
        } else if (options.resultSetType() != null || options.resultSetConcurrency() != null) {
            statement = connection.prepareStatement(
                sql,
                options.resultSetType() == null ? ResultSet.TYPE_FORWARD_ONLY : options.resultSetType(),
                options.resultSetConcurrency() == null ? ResultSet.CONCUR_READ_ONLY : options.resultSetConcurrency()
            );
        } else {
            statement = connection.prepareStatement(sql);
        }
        if (options.fetchSize() != null) {
            statement.setFetchSize(options.fetchSize());
        }
        if (options.maxRows() != null) {
            statement.setMaxRows(options.maxRows());
        }
        if (options.queryTimeoutSeconds() != null) {
            statement.setQueryTimeout(options.queryTimeoutSeconds());
        }
        return statement;
    }

    private static void bindParameters(PreparedStatement statement, List<Parameter> parameters) throws SQLException {
        for (int i = 0; i < parameters.size(); i++) {
            parameters.get(i).binder().set(statement, i + 1);
        }
    }

    private static void closeOnError(@Nullable PreparedStatement statement, SQLException error) {
        if (statement != null) {
            try {
                statement.close();
            } catch (SQLException suppressed) {
                error.addSuppressed(suppressed);
            }
        }
    }

    private static final class OptsBuilderImpl implements OptsBuilder {
        @Nullable
        private Integer fetchSize;
        @Nullable
        private Integer maxRows;
        @Nullable
        private Integer queryTimeoutSeconds;
        @Nullable
        private Integer resultSetType;
        @Nullable
        private Integer resultSetConcurrency;
        @Nullable
        private Integer resultSetHoldability;
        @Nullable
        private Integer autoGeneratedKeys;
        private final List<String> generatedKeyColumns = new ArrayList<>();

        @Override
        public OptsBuilder fetchSize(int fetchSize) {
            this.fetchSize = fetchSize;
            return this;
        }

        @Override
        public OptsBuilder maxRows(int maxRows) {
            this.maxRows = maxRows;
            return this;
        }

        @Override
        public OptsBuilder queryTimeoutSeconds(int seconds) {
            this.queryTimeoutSeconds = seconds;
            return this;
        }

        @Override
        public OptsBuilder resultSetType(int type) {
            this.resultSetType = type;
            return this;
        }

        @Override
        public OptsBuilder resultSetConcurrency(int concurrency) {
            this.resultSetConcurrency = concurrency;
            return this;
        }

        @Override
        public OptsBuilder resultSetHoldability(int holdability) {
            this.resultSetHoldability = holdability;
            return this;
        }

        @Override
        public OptsBuilder generatedKeys(int generatedKeys) {
            this.autoGeneratedKeys = generatedKeys;
            return this;
        }

        @Override
        public OptsBuilder returnGeneratedKeys() {
            this.autoGeneratedKeys = Statement.RETURN_GENERATED_KEYS;
            this.generatedKeyColumns.clear();
            return this;
        }

        @Override
        public OptsBuilder returnGeneratedKeys(String... columns) {
            this.autoGeneratedKeys = null;
            this.generatedKeyColumns.clear();
            this.generatedKeyColumns.addAll(List.of(columns));
            return this;
        }

        @Override
        public JdbcQueryOptions build() {
            return new JdbcQueryOptions(
                this.fetchSize,
                this.maxRows,
                this.queryTimeoutSeconds,
                this.resultSetType,
                this.resultSetConcurrency,
                this.resultSetHoldability,
                this.autoGeneratedKeys,
                this.generatedKeyColumns
            );
        }
    }

    private static final class NamedQueryBuilderImpl implements NamedQueryBuilder {

        private final StringBuilder sql = new StringBuilder();
        private final Map<String, ParameterValue> params = new LinkedHashMap<>();
        private JdbcQueryOptions options = JdbcQueryOptions.DEFAULT;

        @Override
        public NamedQueryBuilder sql(String sql) {
            this.sql.append(Objects.requireNonNull(sql));
            return this;
        }

        @Override
        public NamedQueryBuilder opts(JdbcQueryOptions options) {
            this.options = Objects.requireNonNull(options);
            return this;
        }

        @Override
        public NamedQueryBuilder bind(String name, @Nullable Object value) {
            Objects.requireNonNull(name);
            this.params.put(name, new ParameterValue(value, true, item -> (statement, index) -> statement.setObject(index, item)));
            return this;
        }

        @Override
        public NamedQueryBuilder bind(String name, @Nullable Object value, int sqlType) {
            Objects.requireNonNull(name);
            this.params.put(name, new ParameterValue(value, true, item -> (statement, index) -> {
                if (item == null) {
                    statement.setNull(index, sqlType);
                } else {
                    statement.setObject(index, item, sqlType);
                }
            }));
            return this;
        }

        @Override
        public NamedQueryBuilder bind(String name, @Nullable Object value, SQLType sqlType) {
            Objects.requireNonNull(name);
            Objects.requireNonNull(sqlType);
            this.params.put(name, new ParameterValue(value, true, item -> (statement, index) -> statement.setObject(index, item, sqlType)));
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public <T> NamedQueryBuilder bind(String name, @Nullable T value, JdbcParameterColumnMapper<T> mapper) {
            Objects.requireNonNull(name);
            Objects.requireNonNull(mapper);
            this.params.put(name, new ParameterValue(value, true, item -> (statement, index) -> mapper.set(statement, index, (T) item)));
            return this;
        }

        @Override
        public NamedQueryBuilder bind(String name, JdbcParameterBinder parameter) {
            Objects.requireNonNull(name);
            Objects.requireNonNull(parameter);
            this.params.put(name, new ParameterValue(null, false, item -> parameter));
            return this;
        }

        @Override
        public JdbcQuery build() {
            var sourceSql = this.sql.toString();
            var parsed = parse(sourceSql, this.params);
            return new JdbcQueryImpl(sourceSql, parsed.sql(), parsed.parameters(), this.options);
        }

        @Override
        public NamedBatchBuilder batch() {
            return new NamedBatchBuilderImpl(this.sql.toString(), this.options);
        }
    }

    private static final class TemplateQueryBuilderImpl implements TemplateBuilder {
        private final StringBuilder sql = new StringBuilder();
        private final List<Parameter> parameters = new ArrayList<>();
        private JdbcQueryOptions options = JdbcQueryOptions.DEFAULT;

        @Override
        public TemplateBuilder sql(String sql) {
            this.sql.append(Objects.requireNonNull(sql));
            return this;
        }

        @Override
        public TemplateBuilder opts(JdbcQueryOptions options) {
            this.options = Objects.requireNonNull(options);
            return this;
        }

        @Override
        public TemplateBuilder bind(@Nullable Object value) {
            this.parameters.add(templateParameter(value, item -> (statement, index) -> statement.setObject(index, item)));
            return this;
        }

        @Override
        public TemplateBuilder bind(@Nullable Object value, int sqlType) {
            this.parameters.add(templateParameter(value, item -> (statement, index) -> {
                if (item == null) {
                    statement.setNull(index, sqlType);
                } else {
                    statement.setObject(index, item, sqlType);
                }
            }));
            return this;
        }

        @Override
        public TemplateBuilder bind(@Nullable Object value, SQLType sqlType) {
            Objects.requireNonNull(sqlType);
            this.parameters.add(templateParameter(value, item -> (statement, index) -> statement.setObject(index, item, sqlType)));
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public <T> TemplateBuilder bind(@Nullable T value, JdbcParameterColumnMapper<T> mapper) {
            Objects.requireNonNull(mapper);
            this.parameters.add(templateParameter(value, item -> (statement, index) -> mapper.set(statement, index, (T) item)));
            return this;
        }

        @Override
        public JdbcQuery build() {
            var sourceSql = this.sql.toString();
            return new JdbcQueryImpl(sourceSql, sourceSql, this.parameters, this.options);
        }

        @Override
        public TemplateBatchBuilder batch() {
            return new TemplateBatchBuilderImpl(this.sql.toString(), this.options);
        }
    }

    private static final class NamedBatchBuilderImpl implements NamedBatchBuilder {
        private final String sourceSql;
        private final JdbcQueryOptions options;
        private final List<JdbcQuery> rows = new ArrayList<>();

        private NamedBatchBuilderImpl(String sourceSql, JdbcQueryOptions options) {
            this.sourceSql = sourceSql;
            this.options = options;
        }

        @Override
        public NamedBatchBuilder bind(Map<String, ?> values) {
            var query = JdbcQuery.named()
                .sql(this.sourceSql)
                .opts(this.options)
                .bindAll(values)
                .build();
            this.rows.add(query);
            return this;
        }

        @Override
        public NamedBatchBuilder bind(Consumer<NamedRowBinder> binder) {
            var row = new NamedRowBinderImpl(this.sourceSql, this.options);
            binder.accept(row);
            this.rows.add(row.build());
            return this;
        }

        @Override
        public <T> NamedBatchBuilder bindAllSql(Iterable<T> values, JdbcNamedBatchBinder<T> binder) {
            for (var value : values) {
                var row = new NamedRowBinderImpl(this.sourceSql, this.options);
                try {
                    binder.bind(row, value);
                } catch (SQLException e) {
                    throw new UncheckedSqlException(e);
                }
                this.rows.add(row.build());
            }
            return this;
        }

        @Override
        public JdbcQueryBatch build() {
            return new BatchImpl(this.sourceSql, this.rows.isEmpty() ? this.sourceSql : this.rows.get(0).sql(), this.options, this.rows);
        }
    }

    private static final class TemplateBatchBuilderImpl implements TemplateBatchBuilder {
        private final String sql;
        private final JdbcQueryOptions options;
        private final List<JdbcQuery> rows = new ArrayList<>();

        private TemplateBatchBuilderImpl(String sql, JdbcQueryOptions options) {
            this.sql = sql;
            this.options = options;
        }

        @Override
        public TemplateBatchBuilder bind(@Nullable Object... values) {
            this.rows.add(JdbcQuery.template()
                .sql(this.sql)
                .opts(this.options)
                .bindAll(values)
                .build());
            return this;
        }

        @Override
        public TemplateBatchBuilder bind(Consumer<TemplateRowBinder> binder) {
            var row = new TemplateRowBinderImpl(this.sql, this.options);
            binder.accept(row);
            this.rows.add(row.build());
            return this;
        }

        @Override
        public <T> TemplateBatchBuilder bindAllSql(Iterable<T> values, JdbcTemplateBatchBinder<T> binder) {
            for (var value : values) {
                var row = new TemplateRowBinderImpl(this.sql, this.options);
                try {
                    binder.bind(row, value);
                } catch (SQLException e) {
                    throw new UncheckedSqlException(e);
                }
                this.rows.add(row.build());
            }
            return this;
        }

        @Override
        public JdbcQueryBatch build() {
            return new BatchImpl(this.sql, this.sql, this.options, this.rows);
        }
    }

    private static final class NamedRowBinderImpl implements NamedRowBinder {
        private final NamedQueryBuilder builder;

        private NamedRowBinderImpl(String sourceSql, JdbcQueryOptions options) {
            this.builder = JdbcQuery.named().sql(sourceSql).opts(options);
        }

        @Override
        public NamedRowBinder bind(String name, @Nullable Object value) {
            this.builder.bind(name, value);
            return this;
        }

        @Override
        public NamedRowBinder bind(String name, @Nullable Object value, int sqlType) {
            this.builder.bind(name, value, sqlType);
            return this;
        }

        @Override
        public NamedRowBinder bind(String name, @Nullable Object value, SQLType sqlType) {
            this.builder.bind(name, value, sqlType);
            return this;
        }

        @Override
        public <T> NamedRowBinder bind(String name, @Nullable T value, JdbcParameterColumnMapper<T> mapper) {
            this.builder.bind(name, value, mapper);
            return this;
        }

        private JdbcQuery build() {
            return this.builder.build();
        }
    }

    private static final class TemplateRowBinderImpl implements TemplateRowBinder {
        private final TemplateBuilder builder;

        private TemplateRowBinderImpl(String sql, JdbcQueryOptions options) {
            this.builder = JdbcQuery.template().sql(sql).opts(options);
        }

        @Override
        public TemplateRowBinder bind(@Nullable Object value) {
            this.builder.bind(value);
            return this;
        }

        @Override
        public TemplateRowBinder bind(@Nullable Object value, int sqlType) {
            this.builder.bind(value, sqlType);
            return this;
        }

        @Override
        public TemplateRowBinder bind(@Nullable Object value, SQLType sqlType) {
            this.builder.bind(value, sqlType);
            return this;
        }

        @Override
        public <T> TemplateRowBinder bind(@Nullable T value, JdbcParameterColumnMapper<T> mapper) {
            this.builder.bind(value, mapper);
            return this;
        }

        private JdbcQuery build() {
            return this.builder.build();
        }
    }

    private record BatchImpl(String sourceSql, String sql, JdbcQueryOptions options, List<JdbcQuery> rows) implements JdbcQueryBatch {
        private BatchImpl {
            rows = List.copyOf(rows);
        }

        @Override
        public int size() {
            return this.rows.size();
        }

        @Override
        public List<Parameter> parameters(int index) {
            return this.rows.get(index).parameters();
        }

        @Override
        public PreparedStatement prepare(Connection connection) throws UncheckedSqlException {
            if (this.rows.isEmpty()) {
                throw new IllegalArgumentException("Batch is empty");
            }

            PreparedStatement statement = null;
            try {
                statement = prepareStatement(connection, this.sql, this.options);
                for (var row : this.rows) {
                    bindParameters(statement, row.parameters());
                    statement.addBatch();
                }
                return statement;
            } catch (SQLException e) {
                closeOnError(statement, e);
                throw new UncheckedSqlException(e);
            }
        }
    }

    private static ParsedQuery parse(String sourceSql, Map<String, ParameterValue> params) {
        var sql = new StringBuilder(sourceSql.length());
        var parameters = new ArrayList<Parameter>();
        var usedParams = new ArrayList<String>();
        boolean singleQuoted = false;
        boolean doubleQuoted = false;

        for (int i = 0; i < sourceSql.length(); i++) {
            char c = sourceSql.charAt(i);
            if (c == '\'' && !doubleQuoted) {
                singleQuoted = !singleQuoted;
                sql.append(c);
                continue;
            }
            if (c == '"' && !singleQuoted) {
                doubleQuoted = !doubleQuoted;
                sql.append(c);
                continue;
            }
            if (c != ':' || singleQuoted || doubleQuoted) {
                sql.append(c);
                continue;
            }
            if (i + 1 < sourceSql.length() && sourceSql.charAt(i + 1) == ':') {
                sql.append("::");
                i++;
                continue;
            }
            if (i > 0 && sourceSql.charAt(i - 1) == ':') {
                sql.append(c);
                continue;
            }

            int nameStart = i + 1;
            if (nameStart >= sourceSql.length() || !isNameStart(sourceSql.charAt(nameStart))) {
                sql.append(c);
                continue;
            }

            int nameEnd = nameStart + 1;
            while (nameEnd < sourceSql.length() && isNamePart(sourceSql.charAt(nameEnd))) {
                nameEnd++;
            }

            var name = sourceSql.substring(nameStart, nameEnd);
            if (!params.containsKey(name)) {
                throw new IllegalArgumentException("Parameter '%s' is not specified".formatted(name));
            }
            usedParams.add(name);
            appendParameter(sql, parameters, name, params.get(name));
            i = nameEnd - 1;
        }

        for (var param : params.keySet()) {
            if (!usedParams.contains(param)) {
                throw new IllegalArgumentException("Parameter '%s' is not used in SQL".formatted(param));
            }
        }

        return new ParsedQuery(sql.toString(), parameters);
    }

    private static void appendParameter(StringBuilder sql, List<Parameter> parameters, String name, ParameterValue value) {
        var values = value.expandable()
            ? expand(value.value())
            : null;
        if (values == null) {
            sql.append('?');
            parameters.add(new Parameter(name, value.value(), value.binder(value.value())));
            return;
        }
        if (values.isEmpty()) {
            throw new IllegalArgumentException("Parameter '%s' collection is empty".formatted(name));
        }
        sql.append(String.join(", ", Collections.nCopies(values.size(), "?")));
        for (var item : values) {
            parameters.add(new Parameter(name, item, value.binder(item)));
        }
    }

    @Nullable
    private static List<?> expand(@Nullable Object value) {
        if (value instanceof Collection<?> collection) {
            return new ArrayList<>(collection);
        }
        if (value != null && value.getClass().isArray() && !(value instanceof byte[])) {
            var result = new ArrayList<>();
            for (int i = 0; i < Array.getLength(value); i++) {
                result.add(Array.get(value, i));
            }
            return result;
        }
        return null;
    }

    private static Parameter templateParameter(@Nullable Object value, BinderFactory binderFactory) {
        return new Parameter("", value, binderFactory.create(value));
    }

    private static boolean isNameStart(char c) {
        return Character.isLetter(c) || c == '_';
    }

    private static boolean isNamePart(char c) {
        return Character.isLetterOrDigit(c) || c == '_';
    }

    private record ParameterValue(@Nullable Object value, boolean expandable, BinderFactory binderFactory) {
        JdbcParameterBinder binder(@Nullable Object value) {
            return this.binderFactory.create(value);
        }
    }

    private interface BinderFactory {
        JdbcParameterBinder create(@Nullable Object value);
    }

    private record ParsedQuery(String sql, List<Parameter> parameters) {}

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof JdbcQuery jdbcQuery)) {
            return false;
        }
        return Objects.equals(this.sql, jdbcQuery.sql())
            && Objects.equals(this.parameterValues(), jdbcQuery.parameterValues())
            && Objects.equals(this.options, jdbcQuery.options());
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.sql, this.parameterValues(), this.options);
    }

    @Override
    public String toString() {
        return this.sourceSql;
    }
}
