dependencies {
    annotationProcessor project(':config:config-annotation-processor')

    api project(':scheduling:scheduling-common')
    api libs.db.scheduler

    implementation project(':logging:logging-common')

    testImplementation project(':internal:test-postgres')
    testImplementation libs.flyway
    testImplementation libs.flyway.postgres
}
