plugins {
    alias(libs.plugins.protobuf)
}

apply from: "${project.rootDir}/gradle/kotlin-plugin.gradle"
apply from: "${project.rootDir}/gradle/in-test-generated.gradle"

dependencies {
    api(projects.core.symbolProcessorCommon)

    implementation(projects.core.koraAppSymbolProcessor)

    testImplementation(libs.grpc.kotlin.stub)
    testImplementation(libs.protobuf.kotlin)
    testImplementation(libs.grpc.protobuf)
    testImplementation(projects.grpc.grpcClient)
    testImplementation(projects.config.configSymbolProcessor)
    testImplementation(testFixtures(projects.core.symbolProcessorCommon))
    testImplementation(libs.javax.annotation.api)
}

protobuf {
    protoc {
        artifact = libs.protobuf.protoc.get().toString()
    }
    plugins {
        grpc {
            artifact = libs.grpc.java.gen.get().toString()
        }
        grpckt {
            artifact = "${libs.grpc.kotlin.gen.get()}:jdk8@jar"
        }
    }
    generateProtoTasks {
        ofSourceSet("test").forEach { task ->
            task.plugins {
                grpc
                grpckt
            }
            task.builtins {
                kotlin
            }
        }
    }
}

sourceSets {
    test {
        java {
            def buildDir = layout.buildDirectory
            srcDir(buildDir.dir("generated/source/proto/test/grpc"))
            srcDir(buildDir.dir("generated/source/proto/test/java"))
        }
        kotlin {
            srcDir(layout.buildDirectory.dir("generated/source/proto/test/grpckt"))
        }
    }
}
