plugins {
    alias(libs.plugins.jmh)
    id("java-test-fixtures")
}
apply from: "${project.rootDir}/gradle/kotlin-plugin.gradle"
apply from: "${project.rootDir}/gradle/in-test-generated.gradle"

dependencies {
    api(projects.core.symbolProcessorCommon)
    api(projects.core.koraAppSymbolProcessor)

    testImplementation(projects.json.jsonCommon)
    testImplementation(testFixtures(projects.core.symbolProcessorCommon))
}
