name: Kora test action
description: Kora test action
inputs:
  task-target:
    description: 'Task target name'
    default: 'other'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/master' }}
        gradle-home-cache-cleanup: ${{ github.ref == 'refs/heads/master' }}

    - name: Gradle classes
      run: ./gradlew classes-${{ inputs.task-target }} --scan --no-daemon
      shell: bash

    - name: Gradle javadoc
      run: ./gradlew javadoc-${{ inputs.task-target }} --scan --no-daemon
      shell: bash

    - name: Gradle test classes
      run: ./gradlew testClasses-${{ inputs.task-target }} --scan --no-daemon
      shell: bash

    - name: Gradle test
      run: ./gradlew test-${{ inputs.task-target }} --scan --no-daemon
      shell: bash
