name: Kora test action
description: Kora test action
inputs:
  test-task-name:
    description: 'Test task name'
    default: 'test'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/master' }}
        gradle-home-cache-cleanup: ${{ github.ref == 'refs/heads/master' }}

    - name: Execute Gradle build
      run: ./gradlew ${{ inputs.test-task-name }} --scan --no-daemon
      shell: bash
