package ru.tinkoff.kora.kora.app.ksp.extension

import com.google.devtools.ksp.getClassDeclarationByName
import com.google.devtools.ksp.getConstructors
import com.google.devtools.ksp.isPublic
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSType
import ru.tinkoff.kora.ksp.common.exception.ProcessingErrorException
import ru.tinkoff.kora.ksp.common.generatedClassName

interface KoraExtension {

    fun getDependencyGenerator(resolver: Resolver, type: KSType, tags: Set<String>): (() -> ExtensionResult)?

    fun generatedByProcessor(resolver: Resolver, source: KSClassDeclaration, postfix: String): (() -> ExtensionResult)? {
        val generatedTypeName = source.generatedClassName(postfix)
        val packageName = source.packageName.asString()
        return {
            val maybeGenerated = resolver.getClassDeclarationByName("$packageName.$generatedTypeName")
            if (maybeGenerated == null) {
                ExtensionResult.RequiresCompilingResult
            } else if (maybeGenerated.primaryConstructor != null) {
                ExtensionResult.fromConstructor(maybeGenerated.primaryConstructor!!, maybeGenerated)
            } else {
                // probably generated by java annotation processor
                val constructors = maybeGenerated.getConstructors()
                    .filter { it.isPublic() }
                    .toList()
                if (constructors.size == 1) {
                    ExtensionResult.fromConstructor(constructors[0], maybeGenerated)
                } else {
                    throw ProcessingErrorException("Extension generated type with more than one constructor", maybeGenerated)
                }
            }
        }
    }
}
