apply from: "${project.rootDir}/gradle/in-test-generated.gradle"

dependencies {
    implementation(projects.core.annotationProcessorCommon)
    implementation(projects.aop.aopAnnotationProcessor)
    implementation(libs.javapoet)

    testImplementation(testFixtures(projects.core.annotationProcessorCommon))
    testImplementation(projects.core.annotationProcessorCommon)
    testImplementation(projects.aop.aopAnnotationProcessor)
    testImplementation(projects.core.koraAppAnnotationProcessor)
    testImplementation(projects.config.configAnnotationProcessor)
    testImplementation(projects.config.configHocon)
    testImplementation(projects.internal.testLogging)
    testImplementation(projects.resilient.resilientKora)
    testImplementation(projects.resilient.resilientKoraDistributed)
}
