apply from: "${project.rootDir}/gradle/in-test-generated.gradle"

dependencies {
    implementation(projects.aop.aopAnnotationProcessor)
    implementation(libs.javapoet)

    testImplementation(libs.prometheus.collector.caffeine)
    testImplementation(testFixtures(projects.core.annotationProcessorCommon))
    testImplementation(projects.internal.testLogging)
    testImplementation(projects.cache.cacheCaffeine)
    testImplementation(projects.cache.cacheRedisLettuce)
    testImplementation(projects.json.jsonCommon)
    testImplementation(projects.config.configCommon)
}
