plugins {
    id("java-test-fixtures")
}

apply from: "${project.rootDir}/gradle/kotlin-plugin.gradle"
apply from: "${project.rootDir}/gradle/in-test-generated.gradle"

dependencies {
    annotationProcessor(projects.config.configAnnotationProcessor)

    api(projects.cache.cacheRedisCommon)
    api(projects.redis.redisLettuce)

    testImplementation(projects.internal.testLogging)
    testImplementation(projects.internal.testRedis)
}
