apply from: "${project.rootDir}/gradle/kotlin-plugin.gradle"
apply from: "${project.rootDir}/gradle/in-test-generated.gradle"

dependencies {
    implementation(projects.core.symbolProcessorCommon)
    implementation(projects.aop.aopSymbolProcessor)

    testImplementation(projects.json.jsonCommon)
    testImplementation(projects.json.jsonSymbolProcessor)
    testImplementation(projects.logging.loggingCommon)
    testImplementation(projects.logging.loggingLogback)
    testImplementation(testFixtures(projects.core.symbolProcessorCommon))
}
