package io.koraframework.database.jdbc;

import io.koraframework.database.jdbc.impl.JdbcQueryOptionsImpl;
import org.jspecify.annotations.Nullable;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;

public interface JdbcQueryOptions {

    JdbcQueryOptions DEFAULT = new JdbcQueryOptionsImpl(null, null, null, null, null, null, null, List.of());

    @Nullable
    Integer fetchSize();

    @Nullable
    Integer maxRows();

    @Nullable
    Integer queryTimeoutSeconds();

    @Nullable
    Integer resultSetType();

    @Nullable
    Integer resultSetConcurrency();

    @Nullable
    Integer resultSetHoldability();

    @Nullable
    Integer autoGeneratedKeys();

    List<String> generatedKeyColumns();

    enum ResultSetType {
        FORWARD_ONLY(ResultSet.TYPE_FORWARD_ONLY),
        SCROLL_INSENSITIVE(ResultSet.TYPE_SCROLL_INSENSITIVE),
        SCROLL_SENSITIVE(ResultSet.TYPE_SCROLL_SENSITIVE);

        private final int value;

        ResultSetType(int value) {
            this.value = value;
        }

        public int value() {
            return this.value;
        }
    }

    enum ResultSetConcurrency {
        READ_ONLY(ResultSet.CONCUR_READ_ONLY),
        UPDATABLE(ResultSet.CONCUR_UPDATABLE);

        private final int value;

        ResultSetConcurrency(int value) {
            this.value = value;
        }

        public int value() {
            return this.value;
        }
    }

    enum ResultSetHoldability {
        HOLD_CURSORS_OVER_COMMIT(ResultSet.HOLD_CURSORS_OVER_COMMIT),
        CLOSE_CURSORS_AT_COMMIT(ResultSet.CLOSE_CURSORS_AT_COMMIT);

        private final int value;

        ResultSetHoldability(int value) {
            this.value = value;
        }

        public int value() {
            return this.value;
        }
    }

    enum GeneratedKeys {
        NO_GENERATED_KEYS(Statement.NO_GENERATED_KEYS),
        RETURN_GENERATED_KEYS(Statement.RETURN_GENERATED_KEYS);

        private final int value;

        GeneratedKeys(int value) {
            this.value = value;
        }

        public int value() {
            return this.value;
        }
    }
}
