dependencies {
    annotationProcessor project(":config:config-annotation-processor")

    api project(":core:common")
    api project(":logging:logging-common")
    api project(":config:config-common")
    api project(":telemetry:telemetry-common")
    api libs.jms.api

    testImplementation libs.artemis.server
    testImplementation libs.artemis.jms.client
}
