package io.koraframework.database.jdbc.impl;

import io.koraframework.database.jdbc.JdbcQueryOptions;
import org.jspecify.annotations.Nullable;

import java.util.List;

public record JdbcQueryOptionsImpl(
    @Nullable Integer fetchSize,
    @Nullable Integer maxRows,
    @Nullable Integer queryTimeoutSeconds,
    @Nullable Integer resultSetType,
    @Nullable Integer resultSetConcurrency,
    @Nullable Integer resultSetHoldability,
    @Nullable Integer autoGeneratedKeys,
    List<String> generatedKeyColumns
) implements JdbcQueryOptions {

    public JdbcQueryOptionsImpl {
        generatedKeyColumns = List.copyOf(generatedKeyColumns);
    }
}
