apply from: "${project.rootDir}/gradle/in-test-generated.gradle"

dependencies {
    implementation(projects.core.annotationProcessorCommon)
    implementation(projects.core.koraAppAnnotationProcessor)

    testImplementation(projects.kafka.kafka)
    testImplementation(projects.config.configCommon)
    testImplementation(projects.logging.loggingCommon)
    testImplementation(projects.aop.aopAnnotationProcessor)
    testImplementation(projects.logging.loggingAnnotationProcessor)
    testImplementation(testFixtures(projects.core.annotationProcessorCommon))
}
