plugins {
    id("java-test-fixtures")
}

apply from: "${project.rootDir}/gradle/kotlin-plugin.gradle"
apply from: "${project.rootDir}/gradle/in-test-generated.gradle"

dependencies {
    implementation(projects.core.koraAppSymbolProcessor)
    implementation(libs.ksp.api)
    implementation(libs.kotlin.reflect)
    implementation(libs.kotlinpoet)
    implementation(libs.kotlinpoet.ksp)

    testImplementation(projects.internal.testLogging)
    testImplementation(testFixtures(projects.core.symbolProcessorCommon))
    testImplementation(libs.kotlin.stdlib.lib)
    testImplementation(projects.experimental.camundaZeebeWorker)
    testImplementation(libs.mockito.core)
}
