plugins {
    alias(libs.plugins.protobuf)
}
apply from: "${project.rootDir}/gradle/in-test-generated.gradle"

dependencies {
    api(projects.core.annotationProcessorCommon)

    implementation(projects.core.koraAppAnnotationProcessor)

    testImplementation(libs.grpc.java.gen)
    testImplementation(libs.grpc.protobuf)
    testImplementation(libs.protobuf.java)
    testImplementation(projects.grpc.grpcClient)
    testImplementation(projects.config.configAnnotationProcessor)
    testImplementation(testFixtures(projects.core.annotationProcessorCommon))
    testImplementation(libs.javax.annotation.api)
}

protobuf {
    protoc {
        artifact = libs.protobuf.protoc.get().toString()
    }
    plugins {
        grpc {
            artifact = libs.grpc.java.gen.get().toString()
        }
    }
    generateProtoTasks {
        ofSourceSet("test").forEach {
            it.plugins {
                grpc
            }
        }
    }
}

sourceSets {
    test {
        java {
            def buildDir = layout.buildDirectory
            srcDir(buildDir.dir("generated/source/proto/test/grpc"))
            srcDir(buildDir.dir("generated/source/proto/test/java"))
        }
    }
}
