apply from: "${project.rootDir}/gradle/in-test-generated.gradle"
apply from: "${project.rootDir}/gradle/kotlin-plugin.gradle"

dependencies {
    implementation(projects.core.koraAppSymbolProcessor)

    testImplementation(libs.mapstruct)
    testImplementation(libs.mapstruct.processor)
    testImplementation(libs.jakarta.inject.api)
    testImplementation(projects.core.koraAppSymbolProcessor)
    testImplementation(projects.core.symbolProcessorCommon)
    testImplementation(testFixtures(projects.core.symbolProcessorCommon))
}
