package io.koraframework.kora.app.ksp.extension

import com.google.devtools.ksp.getClassDeclarationByName
import com.google.devtools.ksp.getConstructors
import com.google.devtools.ksp.isPublic
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.squareup.kotlinpoet.ClassName
import io.koraframework.kora.app.ksp.exception.DependencySourceFormatter
import io.koraframework.ksp.common.CommonAopUtils
import io.koraframework.ksp.common.exception.ProcessingErrorException
import io.koraframework.ksp.common.generatedClass

interface KoraExtension {
    fun getDependencyGenerator(resolver: Resolver, type: KSType, tag: String?): (() -> ExtensionResult)?

    fun generatedByProcessor(resolver: Resolver, source: KSClassDeclaration, postfix: String): (() -> ExtensionResult)? {
        val generatedTypeName = source.generatedClass(postfix)
        return generatedByProcessorWithName(resolver, source, generatedTypeName)
    }

    fun generatedByProcessor(resolver: Resolver, source: KSClassDeclaration, postfix: ClassName): (() -> ExtensionResult)? {
        val generatedTypeName = source.generatedClass(postfix)
        return generatedByProcessorWithName(resolver, source, generatedTypeName)
    }


    /**
     * Java annotation processors nest the types generated for one source into a single holder type, e.g. `$Source_Holder.Nested`,
     * while symbol processors generate them as top level types, e.g. `$Source_Postfix`.
     * Source can be compiled by either of them, so top level type is looked up first and then the nested one.
     */
    fun generatedByProcessor(resolver: Resolver, source: KSClassDeclaration, postfix: String, javaHolderPostfix: String, javaNestedName: String): (() -> ExtensionResult)? {
        return generatedByProcessorWithName(resolver, source, source.generatedClass(javaHolderPostfix) + "." + javaNestedName, source.generatedClass(postfix))
    }

    fun generatedByProcessorWithName(resolver: Resolver, source: KSClassDeclaration, generatedTypeName: String): (() -> ExtensionResult)? {
        return generatedByProcessorWithName(resolver, source, generatedTypeName, null)
    }

    fun generatedByProcessorWithName(resolver: Resolver, source: KSClassDeclaration, generatedTypeName: String, fallbackTypeName: String?): (() -> ExtensionResult)? {
        val packageName = source.packageName.asString()
        return ret@{
            val maybeGenerated = resolver.getClassDeclarationByName("$packageName.$generatedTypeName")
                ?: fallbackTypeName?.let { resolver.getClassDeclarationByName("$packageName.$it") }
            if (maybeGenerated == null) {
                throw ProcessingErrorException(
                    """
                    Generated dependency class was not found:
                      expected type: $packageName.$generatedTypeName

                    Fix:
                      - Ensure the symbol/annotation processor that generates this type is enabled.
                      - Compile again after fixing earlier processing errors.
                    """.trimIndent(),
                    source
                )
            }
            if (!CommonAopUtils.hasAopAnnotations(maybeGenerated)) {
                if (maybeGenerated.primaryConstructor != null) {
                    return@ret ExtensionResult.fromConstructor(maybeGenerated.primaryConstructor!!, maybeGenerated)
                }
                // probably generated by java annotation processor
                val constructors = maybeGenerated.getConstructors()
                    .filter { it.isPublic() }
                    .toList()
                if (constructors.size != 1) {
                    throw ProcessingErrorException(
                        """
                        Extension generated type must have exactly one public constructor:
                          generated type: ${maybeGenerated.qualifiedName?.asString()}
                        """.trimIndent() + "\n  found: " + DependencySourceFormatter.constructors(constructors) + "\n\n" + """
                        Fix:
                          - Generate one public constructor.
                          - Make extra constructors non-public.
                        """.trimIndent(),
                        maybeGenerated
                    )
                }
                return@ret ExtensionResult.fromConstructor(constructors[0], maybeGenerated)
            }
            val aopProxy = maybeGenerated.generatedClass("_AopProxy")
            val aopProxyDecl = resolver.getClassDeclarationByName("$packageName.$aopProxy")
            if (aopProxyDecl == null) {
                throw ProcessingErrorException(
                    """
                    Generated AOP proxy class was not found:
                      expected type: $packageName.$aopProxy

                    Fix:
                      - Ensure the AOP symbol/annotation processor is enabled.
                      - Compile again after fixing earlier AOP processing errors.
                    """.trimIndent(),
                    maybeGenerated
                )
            }
            // probably generated by java annotation processor
            val constructors = aopProxyDecl.getConstructors()
                .filter { it.isPublic() }
                .toList()
            if (constructors.size != 1) {
                throw ProcessingErrorException(
                    """
                    Generated AOP proxy type must have exactly one public constructor:
                      generated type: ${aopProxyDecl.qualifiedName?.asString()}
                    """.trimIndent() + "\n  found: " + DependencySourceFormatter.constructors(constructors) + "\n\n" + """
                    Fix:
                      - Generate one public constructor.
                      - Make extra constructors non-public.
                    """.trimIndent(),
                    aopProxyDecl
                )
            }
            return@ret ExtensionResult.fromConstructor(constructors[0], maybeGenerated)
        }
    }
}
