dependencies {
    annotationProcessor project(":config:config-annotation-processor")

    api project(":database:database-jdbc-common")
    api libs.flyway

    testImplementation project(":internal:test-postgres")
    testImplementation project(":database:database-jdbc-hikari")
    testImplementation libs.flyway.postgres
}
