plugins {
    id("java-test-fixtures")
}

dependencies {
    annotationProcessor(projects.config.configAnnotationProcessor)

    api(projects.core.common)
    api(projects.logging.loggingCommon)
    api(projects.telemetry.telemetryCommon)
    api(projects.http.httpCommon)

    testImplementation(projects.config.configHocon)

    testFixturesApi(libs.okhttp)

    testFixturesImplementation(libs.junit.jupiter)
    testFixturesImplementation(libs.assertj)
    testFixturesImplementation(libs.mockito.core)
}
