name: Publish Snapshot

on:
  push:
    branches: [ "master", "2.0" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: JDK 25 setup
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'adopt'

      - name: Gradle setup
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle artifact
        run: ./gradlew assemble

      - name: Gradle publish
        run: ./gradlew publishMavenPublicationToSnapshotRepository -Psigning.secretKeyRingFile=/tmp/secring.gpg --no-daemon --parallel
        env:
          KORA_IO_SIGNING_KEY: ${{ secrets.KORA_IO_SIGNING_KEY }}
          KORA_IO_SIGNING_PASSWORD: ${{ secrets.KORA_IO_SIGNING_PASSWORD }}
          SONATYPE_KORA_IO_USERNAME: ${{ secrets.SONATYPE_KORA_IO_USERNAME }}
          SONATYPE_KORA_IO_PASSWORD: ${{ secrets.SONATYPE_KORA_IO_PASSWORD }}
