name: Run PR tests

on:
  pull_request:
    branches:
      - "master"


permissions:
  contents: read

concurrency:
  group: pr-tests-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-tests:
    if: github.event.pull_request.base.repo.full_name == github.repository
    uses: ./.github/workflows/_run-tests.yml

  dependency-report-artifacts:
    runs-on: ubuntu-26.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: JDK 25 setup
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Generate dependency updates and vulnerability reports
        uses: burrunan/gradle-cache-action@404534c34a2faa40430357a3183522a845b04f3b
        with:
          job-id: compile-step
          arguments: |
            updateLibsVersions
            -PreportVulnerabilities=true
            -PvulnerabilityReportFile=build/reports/dependency-vulnerabilities.md
            -PreportUpdates=true
            -PupdateLevel=patch
            -PupdateReportFile=build/reports/dependency-updates.md
            --console=colored
          save-gradle-dependencies-cache: true
          save-local-build-cache: false
          read-only: true

      - name: Save pull request number
        run: echo "${{ github.event.number }}" > build/reports/pr-number.txt
        shell: bash

      - name: Upload dependency reports
        uses: actions/upload-artifact@v7
        with:
          name: dependency-reports
          path: |
            build/reports/dependency-vulnerabilities.md
            build/reports/dependency-updates.md
            build/reports/pr-number.txt
