name: Run PR tests

on:
  pull_request:
    branches:
      - "master"


permissions:
  contents: read
  checks: write
  pull-requests: write


jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [ 'postgres', 'cassandra', 'redis', 'kafka', 'openapi', 'kotlin-codegen', 'java-codegen', 'other' ]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/test-job
      name: Run ${{ matrix.task }} tests
      with:
        test-task-name: "test-${{ matrix.task }}"
    - name: Publish ${{ matrix.task }} Test Report
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: |
          **/test-results/**/*.xml

  notify:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
    - id: kora_changelog
      run: |
        KORA_CHANGELOG_TAG=1.1.2
        KORA_CHANGELOG_TAG=${KORA_CHANGELOG_TAG//.}
        echo "KORA_CHANGELOG_TAG=${KORA_CHANGELOG_TAG}" >> $GITHUB_OUTPUT

    - name: Notify new release to Telegram
#        KORA_CHANGELOG_TAG=${{ github.event.release.tag_name }}
#        KORA_VERSION: ${{ github.event.release.tag_name }}
      uses: appleboy/telegram-action@master
      env:
        KORA_VERSION: 1.1.2
        KORA_CHANGELOG_TAG: ${{ steps.kora_changelog.outputs.KORA_CHANGELOG_TAG }}
      with:
        to: ${{ secrets.TELEGRAM_RELEASE_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        format: markdown
        message: |
          Вышла новая версия Kora: ${{ env.KORA_VERSION }}

          Больше подробностей [тут](https://kora-projects.github.io/kora-docs/ru/changelog/changelog/#${{ env.KORA_CHANGELOG_TAG }})
