name: Run PR tests

on:
  pull_request:
    branches:
      - "master"


permissions:
  contents: read

concurrency:
  group: pr-tests-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-tests:
    uses: ./.github/workflows/_run-tests.yml

  dependency-report-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: JDK 25 setup
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Gradle setup
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - name: Generate vulnerability report
        run: ./gradlew -I gradle/update-libs-versions.gradle updateLibsVersions -PreportVulnerabilities=true -PvulnerabilityReportFile=build/reports/dependency-vulnerabilities.md --no-daemon --console plain
        shell: bash

      - name: Generate dependency update report
        run: ./gradlew -I gradle/update-libs-versions.gradle updateLibsVersions -PreportUpdates=true -PupdateLevel=patch -PupdateReportFile=build/reports/dependency-updates.md --no-daemon --console plain
        shell: bash

      - name: Save pull request number
        run: echo "${{ github.event.number }}" > build/reports/pr-number.txt
        shell: bash

      - name: Upload dependency reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-reports
          path: |
            build/reports/dependency-vulnerabilities.md
            build/reports/dependency-updates.md
            build/reports/pr-number.txt
