name: Build Master

on:
  push:
    branches:
      - "master"


permissions:
  contents: read

concurrency:
  group: master-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    uses: ./.github/workflows/_run-tests.yml
