name: Run PR tests

on:
  pull_request:
    branches:
      - "master"


permissions:
  contents: read
  checks: write
  pull-requests: write


jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [ 'postgres', 'cassandra', 'redis', 'kafka', 'openapi', 'kotlin-codegen', 'java-codegen', 'other' ]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/test-job
      name: Run ${{ matrix.task }} tests
      with:
        test-task-name: "test-${{ matrix.task }}"
    - name: Publish ${{ matrix.task }} Test Report
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: |
          **/test-results/**/*.xml

    - name: Gradle javadoc
      run: ./gradlew javadoc
      shell: bash
