name: Run PR tests

on:
  pull_request:
    branches:
      - "master"
      - "2.0"


permissions:
  contents: read
  checks: write
  pull-requests: write


jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 35
    strategy:
      matrix:
        task: [ 'postgres', 'cassandra', 'redis', 'kafka', 'openapi', 'codegen-kotlin', 'codegen-java', 'other' ]
    steps:
      - uses: actions/checkout@v4
      - name: JDK 25 setup
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'adopt'

      - name: Gradle setup
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
          gradle-home-cache-cleanup: ${{ github.ref == 'refs/heads/master' }}

      - name: Gradle ${{ matrix.task }} classes
        run: ./gradlew classes-${{ matrix.task }} --scan
        shell: bash

      - name: Gradle ${{ matrix.task }} javadoc
        run: ./gradlew javadoc-${{ matrix.task }} --scan --parallel
        shell: bash

      - name: Gradle ${{ matrix.task }} test classes
        run: ./gradlew testClasses-${{ matrix.task }} --scan
        shell: bash

      - name: Gradle ${{ matrix.task }} test
        run: ./gradlew test-${{ matrix.task }} --scan --parallel
        shell: bash

      - name: Publish ${{ matrix.task }} test report
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            **/test-results/**/*.xml
